version: '3'
services:
  uploader:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./uploads:/uploads
    ports:
      - 5050:3000
    environment:
      - USE_TLS=${USE_TLS}