version: '3'
services:
  uploader:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: reenboog/uploader:latest
    volumes:
    - ./uploads:/uploads
    ports:
      - ${PORT:-5050}:3000
    environment:
      - USE_TLS=${USE_TLS:-true}